@DevTKSS.MyManufacturerERP.Server.WebApi_HostAddress = https://localhost:5000

POST {{DevTKSS.MyManufacturerERP.Server.WebApi_HostAddress}}/todoitems

Content-Type: application/json
{
  "name": "walk dog",
  "isComplete": true
}

###
