version: 2
updates:
  - package-ecosystem: nuget
    directories:
      - "/src"
      - "/.config"
      - "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    ignore:
      - dependency-name: "Yllibed.HttpServer"
      - dependency-name: "Yllibed.HttpServer.Handlers.Uno"
      - dependency-name: "AspNet.Security.OAuth.Etsy"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 1
    commit-message:
      prefix: "deps(gh-actions)"

