// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\shops\{shop_id}\shop-sections\listings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/shop-sections/listings?shop_section_ids={shop_section_ids}{&limit*,offset*,sort_on*,sort_order*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/shop-sections/listings?shop_section_ids={shop_section_ids}{&limit*,offset*,sort_on*,sort_order*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Retrieves all the listings from the section of a specific shop.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListings"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListings?> GetAsync(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder.ListingsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListings> GetAsync(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder.ListingsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListings>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListings.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Retrieves all the listings from the section of a specific shop.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder.ListingsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder.ListingsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Retrieves all the listings from the section of a specific shop.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListingsRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of results to return.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The number of records to skip before selecting the first result.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>A list of numeric IDS for all sections in a specific Etsy shop.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("shop_section_ids")]
            public long?[]? ShopSectionIds { get; set; }
#nullable restore
#else
            [QueryParameter("shop_section_ids")]
            public long?[] ShopSectionIds { get; set; }
#endif
            /// <summary>The value to sort a search result of listings on. NOTES: a) `sort_on` only works when combined with one of the search options (keywords, region, etc.). b) when using `score` the returned results will always be in _descending_ order, regardless of the `sort_order` parameter.</summary>
            [Obsolete("This property is deprecated, use SortOnAsGetSortOnQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_on")]
            public string? SortOn { get; set; }
#nullable restore
#else
            [QueryParameter("sort_on")]
            public string SortOn { get; set; }
#endif
            /// <summary>The value to sort a search result of listings on. NOTES: a) `sort_on` only works when combined with one of the search options (keywords, region, etc.). b) when using `score` the returned results will always be in _descending_ order, regardless of the `sort_order` parameter.</summary>
            [QueryParameter("sort_on")]
            public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.GetSort_onQueryParameterType? SortOnAsGetSortOnQueryParameterType { get; set; }
            /// <summary>The ascending(up) or descending(down) order to sort listings by. NOTE: sort_order only works when combined with one of the search options (keywords, region, etc.).</summary>
            [Obsolete("This property is deprecated, use SortOrderAsGetSortOrderQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_order")]
            public string? SortOrder { get; set; }
#nullable restore
#else
            [QueryParameter("sort_order")]
            public string SortOrder { get; set; }
#endif
            /// <summary>The ascending(up) or descending(down) order to sort listings by. NOTE: sort_order only works when combined with one of the search options (keywords, region, etc.).</summary>
            [QueryParameter("sort_order")]
            public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.GetSort_orderQueryParameterType? SortOrderAsGetSortOrderQueryParameterType { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ListingsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShopSections.Listings.ListingsRequestBuilder.ListingsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
