// System usings
global using System.Security.Claims;
global using System.Text.Json;
global using System.Text.Json.Serialization;
// Project usings
global using DevTKSS.MyManufacturerERP.Server.Models;
global using DevTKSS.MyManufacturerERP.Server.Database;
global using DevTKSS.MyManufacturerERP.Server.Extensions;
global using DevTKSS.MyManufacturerERP.Server.Api.ToDo;
global using DevTKSS.MyManufacturerERP.Server.Api.Identity;
global using DevTKSS.MyManufacturerERP.Server.Api.Common;
global using DevTKSS.MyManufacturerERP.Server.Api.Identity.AllowedOrigins;
// DataContract usings
global using DevTKSS.MyManufacturerERP.DataContracts;
global using DevTKSS.MyManufacturerERP.DataContracts.Serialization;
// Http and authentication usings
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Antiforgery;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Http.HttpResults;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Net.Http.Headers;
global using AspNet.Security.OAuth.Etsy;
// OpenAPI usings
global using Scalar.AspNetCore;
global using Serilog;
// Logging usings
global using Serilog.Templates;
global using Serilog.Templates.Themes;
global using Uno.Wasm.Bootstrap.Server;
global using ILogger = Serilog.ILogger;
// Mapster usings
global using Mapster;