// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\listings\{listing_id}\properties
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PropertiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.listings.item.properties.item collection</summary>
        /// <param name="position">The unique ID of an Etsy [listing property](/documentation/reference#operation/getListingProperties).</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder"/></returns>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("property_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.listings.item.properties.item collection</summary>
        /// <param name="position">The unique ID of an Etsy [listing property](/documentation/reference#operation/getListingProperties).</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("property_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.Item.WithProperty_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings/{listing_id}/properties", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Properties.PropertiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PropertiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings/{listing_id}/properties", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
