// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithUpgrade_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique ID string of a shipping carrier&apos;s mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailClass { get; set; }
#nullable restore
#else
        public string MailClass { get; set; }
#endif
        /// <summary>The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.</summary>
        public int? MaxDeliveryDays { get; set; }
        /// <summary>The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.</summary>
        public int? MinDeliveryDays { get; set; }
        /// <summary>Additional cost of adding the shipping upgrade.</summary>
        public float? Price { get; set; }
        /// <summary>Additional cost of adding the shipping upgrade for each additional item.</summary>
        public float? SecondaryPrice { get; set; }
        /// <summary>The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.</summary>
        public int? ShippingCarrierId { get; set; }
        /// <summary>The type of the shipping upgrade. Domestic (0) or international (1).</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody_type? Type { get; set; }
        /// <summary>Name for the shipping upgrade shown to shoppers at checkout, e.g. USPS Priority.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpgradeName { get; set; }
#nullable restore
#else
        public string UpgradeName { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithUpgrade_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "mail_class", n => { MailClass = n.GetStringValue(); } },
                { "max_delivery_days", n => { MaxDeliveryDays = n.GetIntValue(); } },
                { "min_delivery_days", n => { MinDeliveryDays = n.GetIntValue(); } },
                { "price", n => { Price = n.GetFloatValue(); } },
                { "secondary_price", n => { SecondaryPrice = n.GetFloatValue(); } },
                { "shipping_carrier_id", n => { ShippingCarrierId = n.GetIntValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody_type>(); } },
                { "upgrade_name", n => { UpgradeName = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("mail_class", MailClass);
            writer.WriteIntValue("max_delivery_days", MaxDeliveryDays);
            writer.WriteIntValue("min_delivery_days", MinDeliveryDays);
            writer.WriteFloatValue("price", Price);
            writer.WriteFloatValue("secondary_price", SecondaryPrice);
            writer.WriteIntValue("shipping_carrier_id", ShippingCarrierId);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Upgrades.Item.WithUpgrade_PutRequestBody_type>("type", Type);
            writer.WriteStringValue("upgrade_name", UpgradeName);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
