// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Active;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Batch;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\listings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Active.ActiveRequestBuilder Active
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The batch property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Batch.BatchRequestBuilder Batch
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Batch.BatchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.listings.item collection</summary>
        /// <param name="position">The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder"/></returns>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("listing_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.listings.item collection</summary>
        /// <param name="position">The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("listing_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.WithListing_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.ListingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.ListingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ListingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
