// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>
    /// A representation of an offering for a listing.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingInventoryProductOffering : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether or not the offering has been deleted.</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>Whether or not the offering can be shown to buyers.</summary>
        public bool? IsEnabled { get; set; }
        /// <summary>The ID for the ProductOffering</summary>
        public long? OfferingId { get; set; }
        /// <summary>Price data for this ProductOffering</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? Price { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money Price { get; set; }
#endif
        /// <summary>The quantity the ProductOffering</summary>
        public int? Quantity { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventoryProductOffering"/> and sets the default values.
        /// </summary>
        public ListingInventoryProductOffering()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventoryProductOffering"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventoryProductOffering CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventoryProductOffering();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "is_enabled", n => { IsEnabled = n.GetBoolValue(); } },
                { "offering_id", n => { OfferingId = n.GetLongValue(); } },
                { "price", n => { Price = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteBoolValue("is_enabled", IsEnabled);
            writer.WriteLongValue("offering_id", OfferingId);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("price", Price);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
