// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListingVideo_video_state
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
        [EnumMember(Value = "deleted")]
        #pragma warning disable CS1591
        Deleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "flagged")]
        #pragma warning disable CS1591
        Flagged,
        #pragma warning restore CS1591
    }
}
