// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>
    /// Reference urls and metadata for a video associated with a specific listing.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ListingVideo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The video height dimension in pixels.</summary>
        public int? Height { get; set; }
        /// <summary>The url of the video thumbnail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThumbnailUrl { get; set; }
#nullable restore
#else
        public string ThumbnailUrl { get; set; }
#endif
        /// <summary>The unique ID of a video associated with a listing.</summary>
        public long? VideoId { get; set; }
        /// <summary>The current state of a given video. Value is one of `active`, `inactive`, `deleted` or `flagged`.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo_video_state? VideoState { get; set; }
        /// <summary>The url of the video file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VideoUrl { get; set; }
#nullable restore
#else
        public string VideoUrl { get; set; }
#endif
        /// <summary>The video width dimension in pixels.</summary>
        public int? Width { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo"/> and sets the default values.
        /// </summary>
        public ListingVideo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "height", n => { Height = n.GetIntValue(); } },
                { "thumbnail_url", n => { ThumbnailUrl = n.GetStringValue(); } },
                { "video_id", n => { VideoId = n.GetLongValue(); } },
                { "video_state", n => { VideoState = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo_video_state>(); } },
                { "video_url", n => { VideoUrl = n.GetStringValue(); } },
                { "width", n => { Width = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("height", Height);
            writer.WriteStringValue("thumbnail_url", ThumbnailUrl);
            writer.WriteLongValue("video_id", VideoId);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo_video_state>("video_state", VideoState);
            writer.WriteStringValue("video_url", VideoUrl);
            writer.WriteIntValue("width", Width);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
