// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>
    /// Represents a listing-level return policy.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShopReturnPolicy : IAdditionalDataHolder, IParsable
    {
        /// <summary>return_policy_accepts_exchanges</summary>
        public bool? AcceptsExchanges { get; set; }
        /// <summary>return_policy_accepts_returns</summary>
        public bool? AcceptsReturns { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The deadline for the Return Policy, measured in days. The value must be one of the following: [7, 14, 21, 30, 45, 60, 90].</summary>
        public int? ReturnDeadline { get; set; }
        /// <summary>The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).</summary>
        public long? ReturnPolicyId { get; set; }
        /// <summary>The unique positive non-zero numeric ID for an Etsy Shop.</summary>
        public long? ShopId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReturnPolicy"/> and sets the default values.
        /// </summary>
        public ShopReturnPolicy()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReturnPolicy"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReturnPolicy CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReturnPolicy();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accepts_exchanges", n => { AcceptsExchanges = n.GetBoolValue(); } },
                { "accepts_returns", n => { AcceptsReturns = n.GetBoolValue(); } },
                { "return_deadline", n => { ReturnDeadline = n.GetIntValue(); } },
                { "return_policy_id", n => { ReturnPolicyId = n.GetLongValue(); } },
                { "shop_id", n => { ShopId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("accepts_exchanges", AcceptsExchanges);
            writer.WriteBoolValue("accepts_returns", AcceptsReturns);
            writer.WriteIntValue("return_deadline", ReturnDeadline);
            writer.WriteLongValue("return_policy_id", ReturnPolicyId);
            writer.WriteLongValue("shop_id", ShopId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
