// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>
    /// The record of a purchase from a shop. Shop receipts display monetary values using the shop&apos;s currency.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShopReceipt : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The email address string for the buyer of the listing. It will be null if access hasn&apos;t been granted. Access is case-by-case and subject to approval.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerEmail { get; set; }
#nullable restore
#else
        public string BuyerEmail { get; set; }
#endif
        /// <summary>The numeric ID for the [user](/documentation/reference#tag/User) making the purchase.</summary>
        public long? BuyerUserId { get; set; }
        /// <summary>The city string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The ISO-3166 alpha-2 country code string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryIso { get; set; }
#nullable restore
#else
        public string CountryIso { get; set; }
#endif
        /// <summary>The receipt&apos;s creation time, in epoch seconds.</summary>
        public int? CreatedTimestamp { get; set; }
        /// <summary>The receipt&apos;s creation time, in epoch seconds.</summary>
        public int? CreateTimestamp { get; set; }
        /// <summary>The numeric total discounted price for the receipt when using a discount (percent or fixed) coupon. Free shipping coupons are not included in this discount amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? DiscountAmt { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money DiscountAmt { get; set; }
#endif
        /// <summary>The first address line string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstLine { get; set; }
#nullable restore
#else
        public string FirstLine { get; set; }
#endif
        /// <summary>The formatted shipping address string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FormattedAddress { get; set; }
#nullable restore
#else
        public string FormattedAddress { get; set; }
#endif
        /// <summary>A gift message string the buyer requests delivered with the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GiftMessage { get; set; }
#nullable restore
#else
        public string GiftMessage { get; set; }
#endif
        /// <summary>The name of the person who sent the gift.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GiftSender { get; set; }
#nullable restore
#else
        public string GiftSender { get; set; }
#endif
        /// <summary>The numeric price of gift wrap for this receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? GiftWrapPrice { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money GiftWrapPrice { get; set; }
#endif
        /// <summary>A number equal to the total_price minus the coupon discount plus tax and shipping costs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? Grandtotal { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money Grandtotal { get; set; }
#endif
        /// <summary>When true, the buyer indicated this purchase is a gift.</summary>
        public bool? IsGift { get; set; }
        /// <summary>When true, buyer paid for this purchase.</summary>
        public bool? IsPaid { get; set; }
        /// <summary>When true, seller shipped the products.</summary>
        public bool? IsShipped { get; set; }
        /// <summary>An optional message string from the buyer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageFromBuyer { get; set; }
#nullable restore
#else
        public string MessageFromBuyer { get; set; }
#endif
        /// <summary>The machine-generated acknowledgement string from the payment system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageFromPayment { get; set; }
#nullable restore
#else
        public string MessageFromPayment { get; set; }
#endif
        /// <summary>An optional message string from the seller.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageFromSeller { get; set; }
#nullable restore
#else
        public string MessageFromSeller { get; set; }
#endif
        /// <summary>The name string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The email address string for the email address to which to send payment confirmation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentEmail { get; set; }
#nullable restore
#else
        public string PaymentEmail { get; set; }
#endif
        /// <summary>The payment method string identifying purchaser&apos;s payment method, which must be one of: &apos;cc&apos; (credit card), &apos;paypal&apos;, &apos;check&apos;, &apos;mo&apos; (money order), &apos;bt&apos; (bank transfer), &apos;other&apos;, &apos;ideal&apos;, &apos;sofort&apos;, &apos;apple_pay&apos;, &apos;google&apos;, &apos;android_pay&apos;, &apos;google_pay&apos;, &apos;klarna&apos;, &apos;k_pay_in_4&apos; (klarna), &apos;k_pay_in_3&apos; (klarna), or &apos;k_financing&apos; (klarna).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethod { get; set; }
#nullable restore
#else
        public string PaymentMethod { get; set; }
#endif
        /// <summary>The numeric ID for the [receipt](/documentation/reference#tag/Shop-Receipt) associated to this transaction.</summary>
        public long? ReceiptId { get; set; }
        /// <summary>The numeric value for the Etsy channel that serviced the purchase: 0 for Etsy.com, 1 for a Pattern shop.</summary>
        public int? ReceiptType { get; set; }
        /// <summary>Refunds for a given receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopRefund>? Refunds { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopRefund> Refunds { get; set; }
#endif
        /// <summary>The optional second address line string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SecondLine { get; set; }
#nullable restore
#else
        public string SecondLine { get; set; }
#endif
        /// <summary>The email address string for the seller of the listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SellerEmail { get; set; }
#nullable restore
#else
        public string SellerEmail { get; set; }
#endif
        /// <summary>The numeric ID for the [user](/documentation/reference#tag/User) (seller) fulfilling the purchase.</summary>
        public long? SellerUserId { get; set; }
        /// <summary>A list of shipment statements for this receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptShipment>? Shipments { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptShipment> Shipments { get; set; }
#endif
        /// <summary>The state string for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The current order status string. One of: `paid`, `completed`, `open`, `payment processing` or `canceled`.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt_status? Status { get; set; }
        /// <summary>A number equal to the total_price minus coupon discounts. Does not included tax or shipping costs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? Subtotal { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money Subtotal { get; set; }
#endif
        /// <summary>A number equal to the sum of the individual listings&apos; (price * quantity). Does not included tax or shipping costs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? TotalPrice { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money TotalPrice { get; set; }
#endif
        /// <summary>A number equal to the total shipping cost of the receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? TotalShippingCost { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money TotalShippingCost { get; set; }
#endif
        /// <summary>The total sales tax of the receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? TotalTaxCost { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money TotalTaxCost { get; set; }
#endif
        /// <summary>A number equal to the total value-added tax (VAT) of the receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? TotalVatCost { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money TotalVatCost { get; set; }
#endif
        /// <summary>Array of transactions for the receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptTransaction>? Transactions { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptTransaction> Transactions { get; set; }
#endif
        /// <summary>The time of the last update to the receipt, in epoch seconds.</summary>
        public int? UpdatedTimestamp { get; set; }
        /// <summary>The time of the last update to the receipt, in epoch seconds.</summary>
        public int? UpdateTimestamp { get; set; }
        /// <summary>The zip code string (not necessarily a number) for the recipient in the shipping address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Zip { get; set; }
#nullable restore
#else
        public string Zip { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt"/> and sets the default values.
        /// </summary>
        public ShopReceipt()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buyer_email", n => { BuyerEmail = n.GetStringValue(); } },
                { "buyer_user_id", n => { BuyerUserId = n.GetLongValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "country_iso", n => { CountryIso = n.GetStringValue(); } },
                { "create_timestamp", n => { CreateTimestamp = n.GetIntValue(); } },
                { "created_timestamp", n => { CreatedTimestamp = n.GetIntValue(); } },
                { "discount_amt", n => { DiscountAmt = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "first_line", n => { FirstLine = n.GetStringValue(); } },
                { "formatted_address", n => { FormattedAddress = n.GetStringValue(); } },
                { "gift_message", n => { GiftMessage = n.GetStringValue(); } },
                { "gift_sender", n => { GiftSender = n.GetStringValue(); } },
                { "gift_wrap_price", n => { GiftWrapPrice = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "grandtotal", n => { Grandtotal = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "is_gift", n => { IsGift = n.GetBoolValue(); } },
                { "is_paid", n => { IsPaid = n.GetBoolValue(); } },
                { "is_shipped", n => { IsShipped = n.GetBoolValue(); } },
                { "message_from_buyer", n => { MessageFromBuyer = n.GetStringValue(); } },
                { "message_from_payment", n => { MessageFromPayment = n.GetStringValue(); } },
                { "message_from_seller", n => { MessageFromSeller = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "payment_email", n => { PaymentEmail = n.GetStringValue(); } },
                { "payment_method", n => { PaymentMethod = n.GetStringValue(); } },
                { "receipt_id", n => { ReceiptId = n.GetLongValue(); } },
                { "receipt_type", n => { ReceiptType = n.GetIntValue(); } },
                { "refunds", n => { Refunds = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopRefund>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopRefund.CreateFromDiscriminatorValue)?.AsList(); } },
                { "second_line", n => { SecondLine = n.GetStringValue(); } },
                { "seller_email", n => { SellerEmail = n.GetStringValue(); } },
                { "seller_user_id", n => { SellerUserId = n.GetLongValue(); } },
                { "shipments", n => { Shipments = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptShipment>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptShipment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt_status>(); } },
                { "subtotal", n => { Subtotal = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "total_price", n => { TotalPrice = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "total_shipping_cost", n => { TotalShippingCost = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "total_tax_cost", n => { TotalTaxCost = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "total_vat_cost", n => { TotalVatCost = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "transactions", n => { Transactions = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptTransaction>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptTransaction.CreateFromDiscriminatorValue)?.AsList(); } },
                { "update_timestamp", n => { UpdateTimestamp = n.GetIntValue(); } },
                { "updated_timestamp", n => { UpdatedTimestamp = n.GetIntValue(); } },
                { "zip", n => { Zip = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("buyer_email", BuyerEmail);
            writer.WriteLongValue("buyer_user_id", BuyerUserId);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("country_iso", CountryIso);
            writer.WriteIntValue("created_timestamp", CreatedTimestamp);
            writer.WriteIntValue("create_timestamp", CreateTimestamp);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("discount_amt", DiscountAmt);
            writer.WriteStringValue("first_line", FirstLine);
            writer.WriteStringValue("formatted_address", FormattedAddress);
            writer.WriteStringValue("gift_message", GiftMessage);
            writer.WriteStringValue("gift_sender", GiftSender);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("gift_wrap_price", GiftWrapPrice);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("grandtotal", Grandtotal);
            writer.WriteBoolValue("is_gift", IsGift);
            writer.WriteBoolValue("is_paid", IsPaid);
            writer.WriteBoolValue("is_shipped", IsShipped);
            writer.WriteStringValue("message_from_buyer", MessageFromBuyer);
            writer.WriteStringValue("message_from_payment", MessageFromPayment);
            writer.WriteStringValue("message_from_seller", MessageFromSeller);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("payment_email", PaymentEmail);
            writer.WriteStringValue("payment_method", PaymentMethod);
            writer.WriteLongValue("receipt_id", ReceiptId);
            writer.WriteIntValue("receipt_type", ReceiptType);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopRefund>("refunds", Refunds);
            writer.WriteStringValue("second_line", SecondLine);
            writer.WriteStringValue("seller_email", SellerEmail);
            writer.WriteLongValue("seller_user_id", SellerUserId);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptShipment>("shipments", Shipments);
            writer.WriteStringValue("state", State);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt_status>("status", Status);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("subtotal", Subtotal);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("total_price", TotalPrice);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("total_shipping_cost", TotalShippingCost);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("total_tax_cost", TotalTaxCost);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("total_vat_cost", TotalVatCost);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceiptTransaction>("transactions", Transactions);
            writer.WriteIntValue("updated_timestamp", UpdatedTimestamp);
            writer.WriteIntValue("update_timestamp", UpdateTimestamp);
            writer.WriteStringValue("zip", Zip);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
