// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item
{
    /// <summary>When _updating_ a listing, this value can be either `active` or `inactive`. Note: Setting a `draft` listing to `active` will also publish the listing on etsy.com and requires that the listing have an image set. Setting a `sold_out` listing to active will update the quantity to 1 and renew the listing on etsy.com.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithListing_PatchRequestBody_state
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "inactive")]
        #pragma warning disable CS1591
        Inactive,
        #pragma warning restore CS1591
    }
}
