// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\shops\{shop_id}\receipts\{receipt_id}\tracking
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TrackingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts/{receipt_id}/tracking", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TrackingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts/{receipt_id}/tracking", rawUrl)
        {
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Submits tracking information for a Shop Receipt, which creates a Shop Receipt Shipment entry for the given receipt_id. Each time you successfully submit tracking info, Etsy sends a notification email to the buyer User. When send_bcc is true, Etsy sends shipping notifications to the seller as well. When tracking_code and carrier_name aren&apos;t sent, the receipt is marked as shipped only. If the carrier is not supported, you may use `other` as the carrier name so you can provide the tracking code. **NOTES** When shipping within the United States AND the order is over $10 _or_ when shipping to India, tracking code and carrier name ARE required. Access to ShopReceipt&apos;s first_line, second_line, city, state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 409 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt?> PostAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt> PostAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "409", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Submits tracking information for a Shop Receipt, which creates a Shop Receipt Shipment entry for the given receipt_id. Each time you successfully submit tracking info, Etsy sends a notification email to the buyer User. When send_bcc is true, Etsy sends shipping notifications to the seller as well. When tracking_code and carrier_name aren&apos;t sent, the receipt is marked as shipped only. If the carrier is not supported, you may use `other` as the carrier name so you can provide the tracking code. **NOTES** When shipping within the United States AND the order is over $10 _or_ when shipping to India, tracking code and carrier name ARE required. Access to ShopReceipt&apos;s first_line, second_line, city, state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TrackingRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
