// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\shops\{shop_id}\shipping-profiles\{shipping_profile_id}\destinations\{shipping_profile_destination_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithShipping_profile_destination_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShipping_profile_destination_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations/{shipping_profile_destination_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithShipping_profile_destination_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/shipping-profiles/{shipping_profile_id}/destinations/{shipping_profile_destination_id}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Deletes a shipping destination and removes the destination option from every listing that uses the associated shipping profile. A shipping profile requires at least one shipping destination, so this endpoint cannot delete the final shipping destination for any shipping profile. To delete the final shipping destination from a shipping profile, you must [delete the entire shipping profile](/documentation/reference/#operation/deleteShopShippingProfile).
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            await RequestAdapter.SendNoContentAsync(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Updates an existing shipping destination, which can set or reassign the shipping cost, carrier, and class for a destination.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfileDestination"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfileDestination?> PutAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfileDestination> PutAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "503", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfileDestination>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfileDestination.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Deletes a shipping destination and removes the destination option from every listing that uses the associated shipping profile. A shipping profile requires at least one shipping destination, so this endpoint cannot delete the final shipping destination for any shipping profile. To delete the final shipping destination from a shipping profile, you must [delete the entire shipping profile](/documentation/reference/#operation/deleteShopShippingProfile).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Updates an existing shipping destination, which can set or reassign the shipping cost, carrier, and class for a destination.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithShipping_profile_destination_ItemRequestBuilderDeleteRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithShipping_profile_destination_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
