// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item
{
    /// <summary>The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to &quot;business_days&quot;.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WithShipping_profile_PutRequestBody_processing_time_unit
    {
        [EnumMember(Value = "business_days")]
        #pragma warning disable CS1591
        Business_days,
        #pragma warning restore CS1591
        [EnumMember(Value = "weeks")]
        #pragma warning disable CS1591
        Weeks,
        #pragma warning restore CS1591
    }
}
