// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithShipping_profile_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum processing time the listing needs to ship.</summary>
        public int? MaxProcessingTime { get; set; }
        /// <summary>The minimum time required to process to ship listings with this shipping profile.</summary>
        public int? MinProcessingTime { get; set; }
        /// <summary>The ISO code of the country from which the listing ships.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginCountryIso { get; set; }
#nullable restore
#else
        public string OriginCountryIso { get; set; }
#endif
        /// <summary>The postal code string (not necessarily a number) for the location from which the listing ships. Required if the `origin_country_iso` supports postal codes. See the [Fulfillment Tutorial docs](https://developer.etsy.com/documentation/tutorials/fulfillment/#countries-requiring-postal-codes) for more info</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginPostalCode { get; set; }
#nullable restore
#else
        public string OriginPostalCode { get; set; }
#endif
        /// <summary>The unit used to represent how long a processing time is. A week is equivalent to the set processing schedule (default to 5 business days). If none is provided, the unit is set to &quot;business_days&quot;.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody_processing_time_unit? ProcessingTimeUnit { get; set; }
        /// <summary>The name string of this shipping profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithShipping_profile_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            ProcessingTimeUnit = global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody_processing_time_unit.Business_days;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_processing_time", n => { MaxProcessingTime = n.GetIntValue(); } },
                { "min_processing_time", n => { MinProcessingTime = n.GetIntValue(); } },
                { "origin_country_iso", n => { OriginCountryIso = n.GetStringValue(); } },
                { "origin_postal_code", n => { OriginPostalCode = n.GetStringValue(); } },
                { "processing_time_unit", n => { ProcessingTimeUnit = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody_processing_time_unit>(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("max_processing_time", MaxProcessingTime);
            writer.WriteIntValue("min_processing_time", MinProcessingTime);
            writer.WriteStringValue("origin_country_iso", OriginCountryIso);
            writer.WriteStringValue("origin_postal_code", OriginPostalCode);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.WithShipping_profile_PutRequestBody_processing_time_unit>("processing_time_unit", ProcessingTimeUnit);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
