<Project Sdk="Uno.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0-desktop;$(DefaultTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DevTKSS.Extensions.OAuth.UI.Desktop</RootNamespace>
    <AssemblyName>DevTKSS.Extensions.OAuth.UI.Desktop</AssemblyName>
    <Authors>$(Authors)</Authors>
    <OutputType>Library</OutputType>
    <UnoFeatures>
      Authentication;
      Logging;
    </UnoFeatures>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Yllibed.HttpServer" />
    <PackageReference Include="Yllibed.HttpServer.Handlers.Uno" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OAuth.Validation\DevTKSS.Extensions.OAuth.Validation.csproj" />
    <ProjectReference Include="..\OAuth.UI\DevTKSS.Extensions.OAuth.UI.csproj" />
  </ItemGroup>

</Project>
