// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.Models;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\shops\{shop_id}\receipts
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReceiptsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.shops.item.receipts.item collection</summary>
        /// <param name="position">The numeric ID for the [receipt](/documentation/reference#tag/Shop-Receipt) associated to this transaction.</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder"/></returns>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder this[long position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("receipt_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>Gets an item from the DevTKSS.MyManufacturerERP.Clients.Etsy.v3.application.shops.item.receipts.item collection</summary>
        /// <param name="position">The numeric ID for the [receipt](/documentation/reference#tag/Shop-Receipt) associated to this transaction.</param>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder"/></returns>
        [Obsolete("This indexer is deprecated and will be removed in the next major version. Use the one with the typed parameter instead.")]
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                if (!string.IsNullOrWhiteSpace(position)) urlTplParams.Add("receipt_id", position);
                return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReceiptsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts{?limit*,max_created*,max_last_modified*,min_created*,min_last_modified*,offset*,sort_on*,sort_order*,was_canceled*,was_delivered*,was_paid*,was_shipped*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReceiptsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts{?limit*,max_created*,max_last_modified*,min_created*,min_last_modified*,offset*,sort_on*,sort_order*,was_canceled*,was_delivered*,was_paid*,was_shipped*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Requests the Shop Receipts from a specific Shop, unfiltered or filtered by receipt id range or offset, date, paid, and/or shipped purchases. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipts"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipts?> GetAsync(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder.ReceiptsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipts> GetAsync(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder.ReceiptsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipts>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipts.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Requests the Shop Receipts from a specific Shop, unfiltered or filtered by receipt id range or offset, date, paid, and/or shipped purchases. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder.ReceiptsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder.ReceiptsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Requests the Shop Receipts from a specific Shop, unfiltered or filtered by receipt id range or offset, date, paid, and/or shipped purchases. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReceiptsRequestBuilderGetQueryParameters 
        {
            /// <summary>The maximum number of results to return.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>The latest unix timestamp for when a record was created.</summary>
            [QueryParameter("max_created")]
            public int? MaxCreated { get; set; }
            /// <summary>The latest unix timestamp for when a record last changed.</summary>
            [QueryParameter("max_last_modified")]
            public int? MaxLastModified { get; set; }
            /// <summary>The earliest unix timestamp for when a record was created.</summary>
            [QueryParameter("min_created")]
            public int? MinCreated { get; set; }
            /// <summary>The earliest unix timestamp for when a record last changed.</summary>
            [QueryParameter("min_last_modified")]
            public int? MinLastModified { get; set; }
            /// <summary>The number of records to skip before selecting the first result.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>The value to sort a search result of listings on.</summary>
            [Obsolete("This property is deprecated, use SortOnAsGetSortOnQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_on")]
            public string? SortOn { get; set; }
#nullable restore
#else
            [QueryParameter("sort_on")]
            public string SortOn { get; set; }
#endif
            /// <summary>The value to sort a search result of listings on.</summary>
            [QueryParameter("sort_on")]
            public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.GetSort_onQueryParameterType? SortOnAsGetSortOnQueryParameterType { get; set; }
            /// <summary>The ascending(up) or descending(down) order to sort receipts by.</summary>
            [Obsolete("This property is deprecated, use SortOrderAsGetSortOrderQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort_order")]
            public string? SortOrder { get; set; }
#nullable restore
#else
            [QueryParameter("sort_order")]
            public string SortOrder { get; set; }
#endif
            /// <summary>The ascending(up) or descending(down) order to sort receipts by.</summary>
            [QueryParameter("sort_order")]
            public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.GetSort_orderQueryParameterType? SortOrderAsGetSortOrderQueryParameterType { get; set; }
            /// <summary>When `true`, the endpoint will only return the canceled receipts. When `false`, the endpoint will only return non-canceled receipts.</summary>
            [QueryParameter("was_canceled")]
            public bool? WasCanceled { get; set; }
            /// <summary>When `true`, returns receipts that have been marked as delivered. When `false`, returns receipts where shipment has not been marked as delivered.</summary>
            [QueryParameter("was_delivered")]
            public bool? WasDelivered { get; set; }
            /// <summary>When `true`, returns receipts where the seller has recieved payment for the receipt. When `false`, returns receipts where payment has not been received.</summary>
            [QueryParameter("was_paid")]
            public bool? WasPaid { get; set; }
            /// <summary>When `true`, returns receipts where the seller shipped the product(s) in this receipt. When `false`, returns receipts where shipment has not been set.</summary>
            [QueryParameter("was_shipped")]
            public bool? WasShipped { get; set; }
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ReceiptsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.ReceiptsRequestBuilder.ReceiptsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
