namespace DevTKSS.MyManufacturerERP.Models.Defaults;

/// <summary>
/// oAuth Authorization Response standarized keys from <see href="https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2">4.1.2</see>
/// </summary>
public class OAuthAuthResponseDefaults
{
    /// <summary>
    /// REQUIRED.  The authorization code generated by the
    /// authorization server.The authorization code MUST expire
    /// shortly after it is issued to mitigate the risk of leaks.A
    /// maximum authorization code lifetime of 10 minutes is
    /// RECOMMENDED.The client MUST NOT use the authorization code
    /// more than once.  If an authorization code is used more than
    /// once, the authorization server MUST deny the request and SHOULD
    /// revoke(when possible) all tokens previously issued based on
    /// that authorization code.The authorization code is bound to
    /// the client identifier and redirection URI.
    /// </summary>
    public const string CodeKey = "code";
    /// <summary>
    /// REQUIRED if the "state" parameter was present in the client
    /// authorization request.The exact value received from the client.
    public const string StateKey = "state";
}