// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.Models;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Listings;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Payments;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking;
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Transactions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\shops\{shop_id}\receipts\{receipt_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithReceipt_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The listings property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Listings.ListingsRequestBuilder Listings
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Listings.ListingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payments property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Payments.PaymentsRequestBuilder Payments
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Payments.PaymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tracking property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder Tracking
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Tracking.TrackingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The transactions property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Transactions.TransactionsRequestBuilder Transactions
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.Transactions.TransactionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReceipt_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts/{receipt_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithReceipt_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/shops/{shop_id}/receipts/{receipt_id}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Retrieves a receipt, identified by a receipt id, from an Etsy shop. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Updates the status of a receipt, identified by a receipt id, from an Etsy shop. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 400 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 401 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 403 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 404 status code</exception>
        /// <exception cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt?> PutAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt> PutAsync(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPutRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "401", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "403", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "404", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
                { "500", global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ErrorSchema.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt>(requestInfo, global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopReceipt.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Retrieves a receipt, identified by a receipt id, from an Etsy shop. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;span class=&quot;wt-badge wt-badge--notificationPrimary wt-bg-slime-tint wt-mr-xs-2&quot;&gt;General Release&lt;/span&gt;&lt;a class=&quot;wt-text-link&quot; href=&quot;https://github.com/etsy/open-api/discussions&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Report bug&lt;/a&gt;&lt;/div&gt;&lt;div class=&quot;wt-display-flex-xs wt-align-items-center wt-mt-xs-2 wt-mb-xs-3&quot;&gt;&lt;p class=&quot;wt-text-body-01 banner-text&quot;&gt;This endpoint is ready for production use.&lt;/p&gt;&lt;/div&gt;Updates the status of a receipt, identified by a receipt id, from an Etsy shop. **NOTE** Access to ShopReceipt&apos;s first_line, second_line, city, _state, zip, country_iso and formatted_address is contingent in some regions to a preferred partnership status with Etsy
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPutRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPutRequestInformation(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_PutRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            _ = body ?? throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PUT, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/x-www-form-urlencoded", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Receipts.Item.WithReceipt_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithReceipt_ItemRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithReceipt_ItemRequestBuilderPutRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
