// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings
{
    /// <summary>The ascending(up) or descending(down) order to sort listings by. NOTE: sort_order only works when combined with one of the search options (keywords, region, etc.).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSort_orderQueryParameterType
    {
        [EnumMember(Value = "asc")]
        #pragma warning disable CS1591
        Asc,
        #pragma warning restore CS1591
        [EnumMember(Value = "ascending")]
        #pragma warning disable CS1591
        Ascending,
        #pragma warning restore CS1591
        [EnumMember(Value = "desc")]
        #pragma warning disable CS1591
        Desc,
        #pragma warning restore CS1591
        [EnumMember(Value = "descending")]
        #pragma warning disable CS1591
        Descending,
        #pragma warning restore CS1591
        [EnumMember(Value = "up")]
        #pragma warning disable CS1591
        Up,
        #pragma warning restore CS1591
        [EnumMember(Value = "down")]
        #pragma warning disable CS1591
        Down,
        #pragma warning restore CS1591
    }
}
