// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithListing_PatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A description string of the product for sale in the listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The positive non-zero numeric position in the featured listings of the shop, with rank 1 listings appearing in the left-most position in featured listing on a shop&apos;s home page.</summary>
        public int? FeaturedRank { get; set; }
        /// <summary>An array of numeric image IDs of the images in a listing, which can include up to 10 images.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? ImageIds { get; set; }
#nullable restore
#else
        public List<long?> ImageIds { get; set; }
#endif
        /// <summary>When true, this listing is personalizable. The default value is null.</summary>
        public bool? IsPersonalizable { get; set; }
        /// <summary>When true, tags the listing as a supply product, else indicates that it&apos;s a finished product. Helps buyers locate the listing under the Supplies heading. Requires &apos;who_made&apos; and &apos;when_made&apos;.</summary>
        public bool? IsSupply { get; set; }
        /// <summary>When true, applicable [shop](/documentation/reference#tag/Shop) tax rates apply to this listing at checkout.</summary>
        public bool? IsTaxable { get; set; }
        /// <summary>A string defining the units used to measure the dimensions of the product. Default value is null.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_dimensions_unit? ItemDimensionsUnit { get; set; }
        /// <summary>The numeric height of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemHeight { get; set; }
        /// <summary>The numeric length of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemLength { get; set; }
        /// <summary>The numeric weight of the product measured in units set in &apos;item_weight_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemWeight { get; set; }
        /// <summary>A string defining the units used to measure the weight of the product. Default value is null.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_weight_unit? ItemWeightUnit { get; set; }
        /// <summary>The numeric width of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemWidth { get; set; }
        /// <summary>A list of material strings for materials used in the product. Valid materials strings contain only letters, numbers, and whitespace characters. (regex: /[^\p{L}\p{Nd}\p{Zs}]/u) Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Materials { get; set; }
#nullable restore
#else
        public List<string> Materials { get; set; }
#endif
        /// <summary>This is an integer value representing the maximum length for the personalization message entered by the buyer. Will only change if is_personalizable is &apos;true&apos;.</summary>
        public int? PersonalizationCharCountMax { get; set; }
        /// <summary>A string representing instructions for the buyer to enter the personalization. Will only change if is_personalizable is &apos;true&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalizationInstructions { get; set; }
#nullable restore
#else
        public string PersonalizationInstructions { get; set; }
#endif
        /// <summary>When true, this listing requires personalization. The default value is null. Will only change if is_personalizable is &apos;true&apos;.</summary>
        public bool? PersonalizationIsRequired { get; set; }
        /// <summary>An array of unique IDs of production partner ids.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<long?>? ProductionPartnerIds { get; set; }
#nullable restore
#else
        public List<long?> ProductionPartnerIds { get; set; }
#endif
        /// <summary>The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies). Required for active physical listings. This requirement does not apply to listings of EU-based shops.</summary>
        public long? ReturnPolicyId { get; set; }
        /// <summary>The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.</summary>
        public long? ShippingProfileId { get; set; }
        /// <summary>The numeric ID of the [shop section](/documentation/reference#tag/Shop-Section) for this listing. Default value is null.</summary>
        public int? ShopSectionId { get; set; }
        /// <summary>When true, renews a listing for four months upon expiration.</summary>
        public bool? ShouldAutoRenew { get; set; }
        /// <summary>When _updating_ a listing, this value can be either `active` or `inactive`. Note: Setting a `draft` listing to `active` will also publish the listing on etsy.com and requires that the listing have an image set. Setting a `sold_out` listing to active will update the quantity to 1 and renew the listing on etsy.com.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_state? State { get; set; }
        /// <summary>A comma-separated list of tag strings for the listing. When creating or updating a listing, valid tag strings contain only letters, numbers, whitespace characters, -, &apos;, ™, ©, and ®. (regex: /[^\p{L}\p{Nd}\p{Zs}\-&apos;™©®]/u) Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The numerical taxonomy ID of the listing. See [SellerTaxonomy](/documentation/reference#tag/SellerTaxonomy) and [BuyerTaxonomy](/documentation/reference#tag/BuyerTaxonomy) for more information.</summary>
        public long? TaxonomyId { get; set; }
        /// <summary>The listing&apos;s title string. When creating or updating a listing, valid title strings contain only letters, numbers, punctuation marks, mathematical symbols, whitespace characters, ™, ©, and ®. (regex: /[^\p{L}\p{Nd}\p{P}\p{Sm}\p{Zs}™©®]/u) You can only use the %, :, &amp; and + characters once each.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>An enumerated type string that indicates whether the listing is physical or a digital download.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_type? Type { get; set; }
        /// <summary>An enumerated string for the era in which the maker made the product in this listing. Helps buyers locate the listing under the Vintage heading. Requires &apos;is_supply&apos; and &apos;who_made&apos;.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_when_made? WhenMade { get; set; }
        /// <summary>An enumerated string indicating who made the product. Helps buyers locate the listing under the Handmade heading. Requires &apos;is_supply&apos; and &apos;when_made&apos;.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_who_made? WhoMade { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody"/> and sets the default values.
        /// </summary>
        public WithListing_PatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "featured_rank", n => { FeaturedRank = n.GetIntValue(); } },
                { "image_ids", n => { ImageIds = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "is_personalizable", n => { IsPersonalizable = n.GetBoolValue(); } },
                { "is_supply", n => { IsSupply = n.GetBoolValue(); } },
                { "is_taxable", n => { IsTaxable = n.GetBoolValue(); } },
                { "item_dimensions_unit", n => { ItemDimensionsUnit = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_dimensions_unit>(); } },
                { "item_height", n => { ItemHeight = n.GetFloatValue(); } },
                { "item_length", n => { ItemLength = n.GetFloatValue(); } },
                { "item_weight", n => { ItemWeight = n.GetFloatValue(); } },
                { "item_weight_unit", n => { ItemWeightUnit = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_weight_unit>(); } },
                { "item_width", n => { ItemWidth = n.GetFloatValue(); } },
                { "materials", n => { Materials = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "personalization_char_count_max", n => { PersonalizationCharCountMax = n.GetIntValue(); } },
                { "personalization_instructions", n => { PersonalizationInstructions = n.GetStringValue(); } },
                { "personalization_is_required", n => { PersonalizationIsRequired = n.GetBoolValue(); } },
                { "production_partner_ids", n => { ProductionPartnerIds = n.GetCollectionOfPrimitiveValues<long?>()?.AsList(); } },
                { "return_policy_id", n => { ReturnPolicyId = n.GetLongValue(); } },
                { "shipping_profile_id", n => { ShippingProfileId = n.GetLongValue(); } },
                { "shop_section_id", n => { ShopSectionId = n.GetIntValue(); } },
                { "should_auto_renew", n => { ShouldAutoRenew = n.GetBoolValue(); } },
                { "_state", n => { State = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_state>(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "taxonomy_id", n => { TaxonomyId = n.GetLongValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_type>(); } },
                { "when_made", n => { WhenMade = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_when_made>(); } },
                { "who_made", n => { WhoMade = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_who_made>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("featured_rank", FeaturedRank);
            writer.WriteCollectionOfPrimitiveValues<long?>("image_ids", ImageIds);
            writer.WriteBoolValue("is_personalizable", IsPersonalizable);
            writer.WriteBoolValue("is_supply", IsSupply);
            writer.WriteBoolValue("is_taxable", IsTaxable);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_dimensions_unit>("item_dimensions_unit", ItemDimensionsUnit);
            writer.WriteFloatValue("item_height", ItemHeight);
            writer.WriteFloatValue("item_length", ItemLength);
            writer.WriteFloatValue("item_weight", ItemWeight);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_item_weight_unit>("item_weight_unit", ItemWeightUnit);
            writer.WriteFloatValue("item_width", ItemWidth);
            writer.WriteCollectionOfPrimitiveValues<string>("materials", Materials);
            writer.WriteIntValue("personalization_char_count_max", PersonalizationCharCountMax);
            writer.WriteStringValue("personalization_instructions", PersonalizationInstructions);
            writer.WriteBoolValue("personalization_is_required", PersonalizationIsRequired);
            writer.WriteCollectionOfPrimitiveValues<long?>("production_partner_ids", ProductionPartnerIds);
            writer.WriteLongValue("return_policy_id", ReturnPolicyId);
            writer.WriteLongValue("shipping_profile_id", ShippingProfileId);
            writer.WriteIntValue("shop_section_id", ShopSectionId);
            writer.WriteBoolValue("should_auto_renew", ShouldAutoRenew);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_state>("_state", State);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteLongValue("taxonomy_id", TaxonomyId);
            writer.WriteStringValue("title", Title);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_type>("type", Type);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_when_made>("when_made", WhenMade);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.Listings.Item.WithListing_PatchRequestBody_who_made>("who_made", WhoMade);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
