// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory
{
    /// <summary>An enumerated string that attaches a valid association. Default value is null.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetIncludesQueryParameterType
    {
        [EnumMember(Value = "Listing")]
        #pragma warning disable CS1591
        Listing,
        #pragma warning restore CS1591
    }
}
