// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InventoryPutRequestBody_products : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A list of product offering entries for this product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_offerings>? Offerings { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_offerings> Offerings { get; set; }
#endif
        /// <summary>A list of property value entries for this product. Note: parenthesis characters (`(` and `)`) are not allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_property_values>? PropertyValues { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_property_values> PropertyValues { get; set; }
#endif
        /// <summary>The SKU string for the product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sku { get; set; }
#nullable restore
#else
        public string Sku { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products"/> and sets the default values.
        /// </summary>
        public InventoryPutRequestBody_products()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "offerings", n => { Offerings = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_offerings>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_offerings.CreateFromDiscriminatorValue)?.AsList(); } },
                { "property_values", n => { PropertyValues = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_property_values>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_property_values.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sku", n => { Sku = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_offerings>("offerings", Offerings);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Inventory.InventoryPutRequestBody_products_property_values>("property_values", PropertyValues);
            writer.WriteStringValue("sku", Sku);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
