// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.Models
{
    /// <summary>
    /// A listing from a shop, which contains a product quantity, title, description, price, etc. and additional fields which represent associations.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ShopListingWithAssociations : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The listing&apos;s creation time, in epoch seconds.</summary>
        public int? CreatedTimestamp { get; set; }
        /// <summary>The listing&apos;s creation time, in epoch seconds.</summary>
        public int? CreationTimestamp { get; set; }
        /// <summary>A description string of the product for sale in the listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The listing&apos;s expiration time, in epoch seconds.</summary>
        public int? EndingTimestamp { get; set; }
        /// <summary>The positive non-zero numeric position in the featured listings of the shop, with rank 1 listings appearing in the left-most position in featured listing on a shop&apos;s home page.</summary>
        public int? FeaturedRank { get; set; }
        /// <summary>A string describing the files attached to a digital listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FileData { get; set; }
#nullable restore
#else
        public string FileData { get; set; }
#endif
        /// <summary>When true, the listing has variations.</summary>
        public bool? HasVariations { get; set; }
        /// <summary>Represents a list of listing image resources, each of which contains the reference URLs and metadata for an image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingImage>? Images { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingImage> Images { get; set; }
#endif
        /// <summary>An enumerated string that attaches a valid association. Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventory? Inventory { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventory Inventory { get; set; }
#endif
        /// <summary>When true, a buyer may contact the seller for a customized order. The default value is true when a shop accepts custom orders. Does not apply to shops that do not accept custom orders.</summary>
        public bool? IsCustomizable { get; set; }
        /// <summary>When true, this listing is personalizable. The default value is null.</summary>
        public bool? IsPersonalizable { get; set; }
        /// <summary>When true, this is a private listing intended for a specific buyer and hidden from shop view.</summary>
        public bool? IsPrivate { get; set; }
        /// <summary>When true, tags the listing as a supply product, else indicates that it&apos;s a finished product. Helps buyers locate the listing under the Supplies heading. Requires &apos;who_made&apos; and &apos;when_made&apos;.</summary>
        public bool? IsSupply { get; set; }
        /// <summary>When true, applicable [shop](/documentation/reference#tag/Shop) tax rates apply to this listing at checkout.</summary>
        public bool? IsTaxable { get; set; }
        /// <summary>A string defining the units used to measure the dimensions of the product. Default value is null.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_dimensions_unit? ItemDimensionsUnit { get; set; }
        /// <summary>The numeric length of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemHeight { get; set; }
        /// <summary>The numeric length of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemLength { get; set; }
        /// <summary>The numeric weight of the product measured in units set in &apos;item_weight_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemWeight { get; set; }
        /// <summary>A string defining the units used to measure the weight of the product. Default value is null.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_weight_unit? ItemWeightUnit { get; set; }
        /// <summary>The numeric width of the product measured in units set in &apos;item_dimensions_unit&apos;. Default value is null. If set, the value must be greater than 0.</summary>
        public float? ItemWidth { get; set; }
        /// <summary>The IETF language tag for the default language of the listing. Ex: `de`, `en`, `es`, `fr`, `it`, `ja`, `nl`, `pl`, `pt`, `ru`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The time of the last update to the listing, in epoch seconds.</summary>
        public int? LastModifiedTimestamp { get; set; }
        /// <summary>The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.</summary>
        public long? ListingId { get; set; }
        /// <summary>An enumerated type string that indicates whether the listing is physical or a digital download.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_listing_type? ListingType { get; set; }
        /// <summary>A list of material strings for materials used in the product. Valid materials strings contain only letters, numbers, and whitespace characters. (regex: /[^\p{L}\p{Nd}\p{Zs}]/u) Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Materials { get; set; }
#nullable restore
#else
        public List<string> Materials { get; set; }
#endif
        /// <summary>When true, applicable [shop](/documentation/reference#tag/Shop) tax rates do not apply to this listing at checkout.</summary>
        public bool? NonTaxable { get; set; }
        /// <summary>The number of users who marked this Listing a favorite.</summary>
        public int? NumFavorers { get; set; }
        /// <summary>The listing&apos;s creation time, in epoch seconds.</summary>
        public int? OriginalCreationTimestamp { get; set; }
        /// <summary>This is an integer value representing the maximum length for the personalization message entered by the buyer. Will only change if is_personalizable is &apos;true&apos;.</summary>
        public int? PersonalizationCharCountMax { get; set; }
        /// <summary>When true, this listing requires personalization. The default value is null. Will only change if is_personalizable is &apos;true&apos;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PersonalizationInstructions { get; set; }
#nullable restore
#else
        public string PersonalizationInstructions { get; set; }
#endif
        /// <summary>When true, this listing requires personalization. The default value is null. Will only change if is_personalizable is &apos;true&apos;.</summary>
        public bool? PersonalizationIsRequired { get; set; }
        /// <summary>The positive non-zero price of the product. (Sold product listings are private) Note: The price is the minimum possible price. The [`getListingInventory`](/documentation/reference/#operation/getListingInventory) method requests exact prices for available offerings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money? Price { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money Price { get; set; }
#endif
        /// <summary>The maximum number of days required to process this listing. Default value is null.</summary>
        public int? ProcessingMax { get; set; }
        /// <summary>The minimum number of days required to process this listing. Default value is null.</summary>
        public int? ProcessingMin { get; set; }
        /// <summary>Represents a list of production partners for a shop.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopProductionPartner>? ProductionPartners { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopProductionPartner> ProductionPartners { get; set; }
#endif
        /// <summary>The positive non-zero number of products available for purchase in the listing. Note: The listing quantity is the sum of available offering quantities. You can request the quantities for individual offerings from the ListingInventory resource using the [getListingInventory](/documentation/reference#operation/getListingInventory) endpoint.</summary>
        public int? Quantity { get; set; }
        /// <summary>The numeric ID of the [processing profile](/documentation/reference#operation/getShopReadinessStateDefinition) associated with the listing. Required when listing type is `physical`.</summary>
        public long? ReadinessStateId { get; set; }
        /// <summary>The numeric ID of the [Return Policy](/documentation/reference#operation/getShopReturnPolicies).</summary>
        public long? ReturnPolicyId { get; set; }
        /// <summary>An array of data representing the shipping profile resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfile? ShippingProfile { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfile ShippingProfile { get; set; }
#endif
        /// <summary>The numeric ID of the [shipping profile](/documentation/reference#operation/getShopShippingProfile) associated with the listing. Required when listing type is `physical`.</summary>
        public long? ShippingProfileId { get; set; }
        /// <summary>A shop created by an Etsy user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Shop? Shop { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Shop Shop { get; set; }
#endif
        /// <summary>The unique positive non-zero numeric ID for an Etsy Shop.</summary>
        public long? ShopId { get; set; }
        /// <summary>The numeric ID of a section in a specific Etsy shop.</summary>
        public long? ShopSectionId { get; set; }
        /// <summary>When true, renews a listing for four months upon expiration.</summary>
        public bool? ShouldAutoRenew { get; set; }
        /// <summary>A list of SKU strings for the listing. SKUs will only appear if the requesting user owns the shop and a valid matching OAuthDefaults 2 token is provided. When requested without the token it will be an empty array.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Skus { get; set; }
#nullable restore
#else
        public List<string> Skus { get; set; }
#endif
        /// <summary>When _updating_ a listing, this value can be either `active` or `inactive`. Note: Setting a `draft` listing to `active` will also publish the listing on etsy.com and requires that the listing have an image set. Setting a `sold_out` listing to active will update the quantity to 1 and renew the listing on etsy.com.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_state? State { get; set; }
        /// <summary>The date and time of the last _state change of this listing.</summary>
        public int? StateTimestamp { get; set; }
        /// <summary>An array of style strings for this listing, each of which is free-form text string such as &quot;Formal&quot;, or &quot;Steampunk&quot;. When creating or updating a listing, the listing may have up to two styles. Valid style strings contain only letters, numbers, and whitespace characters. (regex: /[^\p{L}\p{Nd}\p{Zs}]/u) Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Style { get; set; }
#nullable restore
#else
        public List<string> Style { get; set; }
#endif
        /// <summary>A comma-separated list of tag strings for the listing. When creating or updating a listing, valid tag strings contain only letters, numbers, whitespace characters, -, &apos;, ™, ©, and ®. (regex: /[^\p{L}\p{Nd}\p{Zs}\-&apos;™©®]/u) Default value is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The numerical taxonomy ID of the listing. See [SellerTaxonomy](/documentation/reference#tag/SellerTaxonomy) and [BuyerTaxonomy](/documentation/reference#tag/BuyerTaxonomy) for more information.</summary>
        public int? TaxonomyId { get; set; }
        /// <summary>The listing&apos;s title string. When creating or updating a listing, valid title strings contain only letters, numbers, punctuation marks, mathematical symbols, whitespace characters, ™, ©, and ®. (regex: /[^\p{L}\p{Nd}\p{P}\p{Sm}\p{Zs}™©®]/u) You can only use the %, :, &amp; and + characters once each.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>A map of translations for the listing. Default value is a map of all supported languages keyed to null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingTranslations? Translations { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingTranslations Translations { get; set; }
#endif
        /// <summary>The time of the last update to the listing, in epoch seconds.</summary>
        public int? UpdatedTimestamp { get; set; }
        /// <summary>The full URL to the listing&apos;s page on Etsy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Represents a single user of the site</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.User? User { get; set; }
#nullable restore
#else
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.User User { get; set; }
#endif
        /// <summary>The numeric ID for the [user](/documentation/reference#tag/User) posting the listing.</summary>
        public long? UserId { get; set; }
        /// <summary>The single video associated with a listing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo>? Videos { get; set; }
#nullable restore
#else
        public List<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo> Videos { get; set; }
#endif
        /// <summary>The number of times the listing has been viewed. This value is tabulated once per day and **only for active listings**, so the value is not real-time. If `0`, the listing has either not been viewed, not yet tabulated, was not active during the last tabulation or there was an error fetching the value. If a value is expected, call `getListing` to confirm the value.</summary>
        public int? Views { get; set; }
        /// <summary>An enumerated string for the era in which the maker made the product in this listing. Helps buyers locate the listing under the Vintage heading. Requires &apos;is_supply&apos; and &apos;who_made&apos;.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_when_made? WhenMade { get; set; }
        /// <summary>An enumerated string indicating who made the product. Helps buyers locate the listing under the Handmade heading. Requires &apos;is_supply&apos; and &apos;when_made&apos;.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_who_made? WhoMade { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations"/> and sets the default values.
        /// </summary>
        public ShopListingWithAssociations()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_timestamp", n => { CreatedTimestamp = n.GetIntValue(); } },
                { "creation_timestamp", n => { CreationTimestamp = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "ending_timestamp", n => { EndingTimestamp = n.GetIntValue(); } },
                { "featured_rank", n => { FeaturedRank = n.GetIntValue(); } },
                { "file_data", n => { FileData = n.GetStringValue(); } },
                { "has_variations", n => { HasVariations = n.GetBoolValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingImage>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingImage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "inventory", n => { Inventory = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventory>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventory.CreateFromDiscriminatorValue); } },
                { "is_customizable", n => { IsCustomizable = n.GetBoolValue(); } },
                { "is_personalizable", n => { IsPersonalizable = n.GetBoolValue(); } },
                { "is_private", n => { IsPrivate = n.GetBoolValue(); } },
                { "is_supply", n => { IsSupply = n.GetBoolValue(); } },
                { "is_taxable", n => { IsTaxable = n.GetBoolValue(); } },
                { "item_dimensions_unit", n => { ItemDimensionsUnit = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_dimensions_unit>(); } },
                { "item_height", n => { ItemHeight = n.GetFloatValue(); } },
                { "item_length", n => { ItemLength = n.GetFloatValue(); } },
                { "item_weight", n => { ItemWeight = n.GetFloatValue(); } },
                { "item_weight_unit", n => { ItemWeightUnit = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_weight_unit>(); } },
                { "item_width", n => { ItemWidth = n.GetFloatValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "last_modified_timestamp", n => { LastModifiedTimestamp = n.GetIntValue(); } },
                { "listing_id", n => { ListingId = n.GetLongValue(); } },
                { "listing_type", n => { ListingType = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_listing_type>(); } },
                { "materials", n => { Materials = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "non_taxable", n => { NonTaxable = n.GetBoolValue(); } },
                { "num_favorers", n => { NumFavorers = n.GetIntValue(); } },
                { "original_creation_timestamp", n => { OriginalCreationTimestamp = n.GetIntValue(); } },
                { "personalization_char_count_max", n => { PersonalizationCharCountMax = n.GetIntValue(); } },
                { "personalization_instructions", n => { PersonalizationInstructions = n.GetStringValue(); } },
                { "personalization_is_required", n => { PersonalizationIsRequired = n.GetBoolValue(); } },
                { "price", n => { Price = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money.CreateFromDiscriminatorValue); } },
                { "processing_max", n => { ProcessingMax = n.GetIntValue(); } },
                { "processing_min", n => { ProcessingMin = n.GetIntValue(); } },
                { "production_partners", n => { ProductionPartners = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopProductionPartner>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopProductionPartner.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "readiness_state_id", n => { ReadinessStateId = n.GetLongValue(); } },
                { "return_policy_id", n => { ReturnPolicyId = n.GetLongValue(); } },
                { "shipping_profile", n => { ShippingProfile = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfile>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfile.CreateFromDiscriminatorValue); } },
                { "shipping_profile_id", n => { ShippingProfileId = n.GetLongValue(); } },
                { "shop", n => { Shop = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Shop>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Shop.CreateFromDiscriminatorValue); } },
                { "shop_id", n => { ShopId = n.GetLongValue(); } },
                { "shop_section_id", n => { ShopSectionId = n.GetLongValue(); } },
                { "should_auto_renew", n => { ShouldAutoRenew = n.GetBoolValue(); } },
                { "skus", n => { Skus = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "_state", n => { State = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_state>(); } },
                { "state_timestamp", n => { StateTimestamp = n.GetIntValue(); } },
                { "style", n => { Style = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "taxonomy_id", n => { TaxonomyId = n.GetIntValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "translations", n => { Translations = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingTranslations>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingTranslations.CreateFromDiscriminatorValue); } },
                { "updated_timestamp", n => { UpdatedTimestamp = n.GetIntValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.User>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.User.CreateFromDiscriminatorValue); } },
                { "user_id", n => { UserId = n.GetLongValue(); } },
                { "videos", n => { Videos = n.GetCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo>(global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo.CreateFromDiscriminatorValue)?.AsList(); } },
                { "views", n => { Views = n.GetIntValue(); } },
                { "when_made", n => { WhenMade = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_when_made>(); } },
                { "who_made", n => { WhoMade = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_who_made>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("created_timestamp", CreatedTimestamp);
            writer.WriteIntValue("creation_timestamp", CreationTimestamp);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("ending_timestamp", EndingTimestamp);
            writer.WriteIntValue("featured_rank", FeaturedRank);
            writer.WriteStringValue("file_data", FileData);
            writer.WriteBoolValue("has_variations", HasVariations);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingImage>("images", Images);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingInventory>("inventory", Inventory);
            writer.WriteBoolValue("is_customizable", IsCustomizable);
            writer.WriteBoolValue("is_personalizable", IsPersonalizable);
            writer.WriteBoolValue("is_private", IsPrivate);
            writer.WriteBoolValue("is_supply", IsSupply);
            writer.WriteBoolValue("is_taxable", IsTaxable);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_dimensions_unit>("item_dimensions_unit", ItemDimensionsUnit);
            writer.WriteFloatValue("item_height", ItemHeight);
            writer.WriteFloatValue("item_length", ItemLength);
            writer.WriteFloatValue("item_weight", ItemWeight);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_item_weight_unit>("item_weight_unit", ItemWeightUnit);
            writer.WriteFloatValue("item_width", ItemWidth);
            writer.WriteStringValue("language", Language);
            writer.WriteIntValue("last_modified_timestamp", LastModifiedTimestamp);
            writer.WriteLongValue("listing_id", ListingId);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_listing_type>("listing_type", ListingType);
            writer.WriteCollectionOfPrimitiveValues<string>("materials", Materials);
            writer.WriteBoolValue("non_taxable", NonTaxable);
            writer.WriteIntValue("num_favorers", NumFavorers);
            writer.WriteIntValue("original_creation_timestamp", OriginalCreationTimestamp);
            writer.WriteIntValue("personalization_char_count_max", PersonalizationCharCountMax);
            writer.WriteStringValue("personalization_instructions", PersonalizationInstructions);
            writer.WriteBoolValue("personalization_is_required", PersonalizationIsRequired);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Money>("price", Price);
            writer.WriteIntValue("processing_max", ProcessingMax);
            writer.WriteIntValue("processing_min", ProcessingMin);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopProductionPartner>("production_partners", ProductionPartners);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteLongValue("readiness_state_id", ReadinessStateId);
            writer.WriteLongValue("return_policy_id", ReturnPolicyId);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopShippingProfile>("shipping_profile", ShippingProfile);
            writer.WriteLongValue("shipping_profile_id", ShippingProfileId);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.Shop>("shop", Shop);
            writer.WriteLongValue("shop_id", ShopId);
            writer.WriteLongValue("shop_section_id", ShopSectionId);
            writer.WriteBoolValue("should_auto_renew", ShouldAutoRenew);
            writer.WriteCollectionOfPrimitiveValues<string>("skus", Skus);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_state>("_state", State);
            writer.WriteIntValue("state_timestamp", StateTimestamp);
            writer.WriteCollectionOfPrimitiveValues<string>("style", Style);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteIntValue("taxonomy_id", TaxonomyId);
            writer.WriteStringValue("title", Title);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingTranslations>("translations", Translations);
            writer.WriteIntValue("updated_timestamp", UpdatedTimestamp);
            writer.WriteStringValue("url", Url);
            writer.WriteObjectValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.User>("user", User);
            writer.WriteLongValue("user_id", UserId);
            writer.WriteCollectionOfObjectValues<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ListingVideo>("videos", Videos);
            writer.WriteIntValue("views", Views);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_when_made>("when_made", WhenMade);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.Models.ShopListingWithAssociations_who_made>("who_made", WhoMade);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
