// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithShipping_profile_destination_PutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The ISO code of the country to which the listing ships. If null, request sets destination to destination_region. Required if destination_region is null or not provided.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DestinationCountryIso { get; set; }
#nullable restore
#else
        public string DestinationCountryIso { get; set; }
#endif
        /// <summary>The code of the region to which the listing ships. A region represents a set of countries. Supported regions are Europe Union and Non-Europe Union (countries in Europe not in EU). If `none`, request sets destination to destination_country_iso. Required if destination_country_iso is null or not provided.</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody_destination_region? DestinationRegion { get; set; }
        /// <summary>The unique ID string of a shipping carrier&apos;s mail class, which is used to calculate an estimated delivery date. **Required with `shipping_carrier_id`** if `min_delivery_days` and `max_delivery_days` are null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailClass { get; set; }
#nullable restore
#else
        public string MailClass { get; set; }
#endif
        /// <summary>The maximum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `min_delivery_days`** if `mail_class` is null.</summary>
        public int? MaxDeliveryDays { get; set; }
        /// <summary>The minimum number of business days a buyer can expect to wait to receive their purchased item once it has shipped. **Required with `max_delivery_days`** if `mail_class` is null.</summary>
        public int? MinDeliveryDays { get; set; }
        /// <summary>The cost of shipping to this country/region alone, measured in the store&apos;s default currency.</summary>
        public float? PrimaryCost { get; set; }
        /// <summary>The cost of shipping to this country/region with another item, measured in the store&apos;s default currency.</summary>
        public float? SecondaryCost { get; set; }
        /// <summary>The unique ID of a supported shipping carrier, which is used to calculate an Estimated Delivery Date. **Required with `mail_class`** if `min_delivery_days` and `max_delivery_days` are null.</summary>
        public int? ShippingCarrierId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody"/> and sets the default values.
        /// </summary>
        public WithShipping_profile_destination_PutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
            DestinationRegion = global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody_destination_region.None;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "destination_country_iso", n => { DestinationCountryIso = n.GetStringValue(); } },
                { "destination_region", n => { DestinationRegion = n.GetEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody_destination_region>(); } },
                { "mail_class", n => { MailClass = n.GetStringValue(); } },
                { "max_delivery_days", n => { MaxDeliveryDays = n.GetIntValue(); } },
                { "min_delivery_days", n => { MinDeliveryDays = n.GetIntValue(); } },
                { "primary_cost", n => { PrimaryCost = n.GetFloatValue(); } },
                { "secondary_cost", n => { SecondaryCost = n.GetFloatValue(); } },
                { "shipping_carrier_id", n => { ShippingCarrierId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("destination_country_iso", DestinationCountryIso);
            writer.WriteEnumValue<global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Shops.Item.ShippingProfiles.Item.Destinations.Item.WithShipping_profile_destination_PutRequestBody_destination_region>("destination_region", DestinationRegion);
            writer.WriteStringValue("mail_class", MailClass);
            writer.WriteIntValue("max_delivery_days", MaxDeliveryDays);
            writer.WriteIntValue("min_delivery_days", MinDeliveryDays);
            writer.WriteFloatValue("primary_cost", PrimaryCost);
            writer.WriteFloatValue("secondary_cost", SecondaryCost);
            writer.WriteIntValue("shipping_carrier_id", ShippingCarrierId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
