// <auto-generated/>
#pragma warning disable CS0618
using DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item.Offerings;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v3\application\listings\{listing_id}\products\{product_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProduct_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The offerings property</summary>
        public global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item.Offerings.OfferingsRequestBuilder Offerings
        {
            get => new global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item.Offerings.OfferingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item.WithProduct_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProduct_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings/{listing_id}/products/{product_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::DevTKSS.MyManufacturerERP.Clients.Etsy.V3.Application.Listings.Item.Products.Item.WithProduct_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProduct_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v3/application/listings/{listing_id}/products/{product_id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
